CREATE DATABASE IF NOT EXISTS DB_LOCADORA;


USE DB_LOCADORA;

CREATE TABLE IF NOT EXISTS TB_SEXOS(
	SEX_ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT, 
	SEX_NOME VARCHAR(15) NOT NULL, 
	SEX_SIGLA CHAR(1) NOT NULL,
    CONSTRAINT PRIMARY KEY(SEX_ID)
);

INSERT INTO TB_SEXOS 
	(SEX_NOME, SEX_SIGLA) 
VALUES 
	('MASCULINO', 'M'), 
	('FEMININO', 'F');
    
USE DB_LOCADORA;    
    
    
 CREATE TABLE IF NOT EXISTS TB_CATEGORIAS(
 CAT_ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT, 
 CAT_NOME VARCHAR(25) NOT NULL,
 CAT_PRECO DECIMAL(2,2) NOT NULL,
 CONSTRAINT PRIMARY KEY(CAT_ID)
 );
 
 INSERT INTO TB_CATEGORIAS 
	(CAT_NOME,CAT_PRECO)
 VALUES
	('CATALOGO',1.50),
    ('LAÇAMENTO', 3.00),
    ('SUPERLANÇAMENTO',5.00);
    

USE DB_LOCADORA;

CREATE TABLE IF NOT EXISTS TB_GENEROS(
GEN_ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
GEN_NOME VARCHAR(20),
CONSTRAINT PRIMARY KEY(GEN_ID)
);

INSERT INTO TB_GENEROS 
(GEN_NOME)
VALUES
	('AÇÃO'),
    ('FICÇÃO'),
    ('FANTASIA'),
    ('COMÉDIA'),
    ('ROMANCE');


USE DB_LOCADORA;

CREATE TABLE IF NOT EXISTS TB_ATORES( 
ATO_ID INT UNSIGNED NOT NULL AUTO_INCREMENT, 
ATO_FIL_ID INT UNSIGNED NOT NULL, 
ATO_NOME VARCHAR(50),
CONSTRAINT PRIMARY KEY(ATO_ID)
);

INSERT INTO TB_ATORES
	(ATO_NOME)
 VALUES
	('LUAN'),('HUDSON'),('GIZILLE'),('RAFAEL'),
    ('VICTOR'),('FABIANO'),('WESKLEY');


USE DB_LOCADORA;

CREATE TABLE IF NOT EXISTS TB_DIRETORES(
DIR_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
DIR_NOME VARCHAR(50),
CONSTRAINT PRIMARY KEY(DIR_ID)
);

INSERT INTO TB_DIRETORES
	(DIR_NOME)
 VALUES
	('JOSÉ'),('JOÃO'),('PEDRO'),('PAULO'),
    ('MARIA'),('SANTANA'),('LUCAS
    ');

USE DB_LOCADORA;

CREATE TABLE IF NOT EXISTS TB_CLASSIFICACOES(
CLA_ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
CLA_NOME VARCHAR(20) NOT NULL,
CLA_SIGLA VARCHAR(2) NOT NULL,
CONSTRAINT PRIMARY KEY(CLA_ID)
);

INSERT INTO TB_CLASSIFICACOES
	(CLA_NOME, CLA_SIGLA)
VALUES
 ('LIVRES', 'L'),
 ('10 ANOS', '10'),
 ('12 ANOS','12'),
 ('14 ANOS','14'),
 ('16 ANOS','16'),
 ('18 ANOS','18');

USE DB_LOCADORA;

CREATE TABLE IF NOT EXISTS TB_FILMES(
	FIL_ID INT UNSIGNED NOT NULL AUTO_INCREMENT, 
	FIL_TITULO VARCHAR(80) NOT NULL, 
	FIL_SINOPSE TEXT, 
	FIL_ANO_LANCAMENTO SMALLINT UNSIGNED, 
	FIL_DURACAO SMALLINT UNSIGNED,
    FIL_CLA_ID TINYINT UNSIGNED NOT NULL,
    FIL_CAT_ID TINYINT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY(FIL_ID),
    CONSTRAINT FK_CAT_FIL FOREIGN KEY(FIL_CAT_ID) REFERENCES TB_CATEGORIAS(CAT_ID),
    CONSTRAINT FK_CLA_FIL FOREIGN KEY(FIL_CLA_ID) REFERENCES TB_CLASSIFICACOES(CLA_ID)    
);


INSERT INTO TB_FILMES
	(FIL_TITULO, FIL_ANO_LANCAMENTO , FIL_DURACAO, FIL_CLA_ID, FIL_CAT_ID)
VALUES
	('SENHOR DOS ANÉIS - SOCIEDADE DO ANEL', 2002, 300, 3 , 1),
    ('VELOZES E FURIOSOS', 2001, 120, 4 , 1),
    ('VINGADORES: GUERRA INFINITA',2018, 300, 4, 3),
    ('HOMEM DE FERRO 3', 2013, 140, 3, 2),
    ('TRANSFORMERS: O ULTIMO CAVALEIRO',2017, 120, 3 , 2),
    ('PIXELS',2015, 132, 2, 2),
    ('O IMPOSTOR', 2014, 140, 6, 2);
    
    
USE DB_LOCADORA;

CREATE TABLE IF NOT EXISTS TB_STATUS(
STT_ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
STT_STATUS VARCHAR(20) NOT NULL,
CONSTRAINT PRIMARY KEY(STT_ID)
);

INSERT INTO TB_STATUS 
	(STT_STATUS)
VALUES
	('DISPONIVEL,INDISPONIVEL');
    
USE DB_LOCADORA;

CREATE TABLE IF NOT EXISTS TB_MIDIAS(
MID_ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT, 
MID_NOME VARCHAR(10) NOT NULL,
CONSTRAINT PRIMARY KEY(MID_ID)
);

INSERT INTO TB_MIDIAS 
	(MID_NOME)
VALUES
	('BLU-RAY','DVD');
    
USE DB_LOCADORA;

CREATE TABLE IF NOT EXISTS TB_COPIAS(
COP_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
COP_STT_ID TINYINT UNSIGNED NOT NULL,
COP_MID_ID TINYINT UNSIGNED NOT NULL,
CONSTRAINT PRIMARY KEY(COP_ID),
CONSTRAINT FK_COP_STT FOREIGN KEY (COP_STT_ID) REFERENCES TB_STATUS(STT_ID),
CONSTRAINT FK_COP_MID FOREIGN KEY (COP_MID_ID) REFERENCES TB_MIDIAS(MID_ID)
);


USE DB_LOCADORA;

CREATE TABLE IF NOT EXISTS TB_GENEROS_FILMES(
	GDF_FIL_ID INT UNSIGNED NOT NULL,
    GDF_GEN_ID TINYINT UNSIGNED NOT NULL,
    CONSTRAINT PRIMARY KEY(GDF_FIL_ID,GDF_GEN_ID),
    CONSTRAINT FK_FIL_GDF FOREIGN KEY(GDF_FIL_ID) REFERENCES TB_FILMES(FIL_ID),
    CONSTRAINT FK_GEN_GDF FOREIGN KEY(GDF_GEN_ID) REFERENCES TB_GENEROS(GEN_ID)
    );
    
INSERT INTO TB_GENEROS_FILMES
		(GDF_FIL_ID, GDF_GEN_ID)
VALUES
	(1,1), (1,4),
    (2,7),
    (3,7),(3,8);
    
USE DB_LOCADORA;

CREATE TABLE IF NOT EXISTS TB_IDIOMAS(
IDIO_ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
IDIO_NOME VARCHAR(50) NOT NULL,
CONSTRAINT PRIMARY KEY(IDIO_ID)
);

INSERT INTO TB_IDIOMAS
	(IDIO_NOME)
VALUES
('PORTUGUÊS'),
('INGLÊS'),
('ESPANHOL');

USE DB_LOCADORA;

CREATE TABLE IF NOT EXISTS TB_OBSERVACOES_COPIAS(
ODC_OBSERVACAO TEXT NOT NULL,
ODC_COP_ID INT NOT NULL,
CONSTRAINT PRIMARY KEY(ODC_OBSERVACAO, ODC_COP_ID),
CONSTRAINT FK_COP_ODC FOREIGN KEY(ODC_COP_ID) REFERENCES TB_COPIAS(COP_ID)
);

USE DB_LOCADORA;

CREATE TABLE IF NOT EXISTS TB_PAISES(
	PAI_ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT, 
    PAI_NOME VARCHAR(30) NOT NULL, 
    PAI_SIGLA CHAR(3) NOT NULL,
    CONSTRAINT PRIMARY KEY(PAI_ID)
);

INSERT INTO TB_PAISES 
	(PAI_SIGLA,PAI_NOME)
VALUES
	('BRA', 'BRASIL'),
    ('USA','ESTADOS UNIDOS'),
    ('FRA','FRANÇA'),
    ('ITA','ITÁLIA');
 
 
USE DB_LOCADORA;

ALTER TABLE TB_FILMES
ADD COLUMN FIL_PAI_ID TINYINT UNSIGNED NOT NULL DEFAULT 2;

ALTER TABLE TB_FILMES 
ADD CONSTRAINT FK_PAI_FIL FOREIGN KEY(FIL_PAI_ID)
REFERENCES TB_PAISES(PAI_ID);

USE DB_LOCADORA;

CREATE TABLE IF NOT EXISTS TB_FONES_CLIENTES(
FDC_FONE_CLIENTE VARCHAR (12) NOT NULL AUTO_INCREMENT
);



USE DB_LOCADORA;

CREATE TABLE IF NOT EXISTS TB_CLIENTES(
	CLI_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    CLI_NOME VARCHAR(50)NOT NULL,
    CONSTRAINT PRIMARY KEY(CLI_ID),
    CONSTRAINT FK_FDC_CLI FOREIGN KEY(CLI_FDC_ID) REFERENCES TB_FONES_CLIENTES
);

INSERT INTO TB_CLIENTES
	(CLI_ID,CLI_NOME)
VALUES
	('HUDSON'),
    ('RAFAEL'),
    ('LUAN'),
    ('FABIANO'),
    ('GIZELLE'),
    ('VICTOR');








